<?xml version="1.0" encoding="utf-8"?><Database Name="asdf" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2HM0EJ8\SQLEXPRESS;Initial Catalog=asdf;Integrated Security=True" SettingsObjectName="ConsoleApp4.Properties.Settings" SettingsPropertyName="asdfConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table_1" Member="Table_1">
    <Type Name="Table_1">
      <Column Name="x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="y" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>